### ISSUE TITLE
EchoSim error, following step by step

### ISSUE THREAD

**Issue by 5tigerjelly** [INFO461-Team-Go/ohana#101]
![image](https://user-images.githubusercontent.com/15973528/40896029-87c37ad6-6767-11e8-83e9-562a91da2fc4.png)

I followed every step on the email, but I get an error everytime I send a request. 
I allowed mic to the chrome and safari browser. 

Both did not work. It seems to record what I am saying, but just saids there was an error.

**Comment by akkarh** [comment]
Thanks, for the heads up Chris! We posted a new guide with an alternate app to run the skill. I apologize for any inconvenience!
