### ISSUE TITLE
Cannot access O'Hana Skill

### ISSUE THREAD

**Issue by abegel** [INFO461-Team-Go/ohana#103]
I clicked on the beta test link sent by Harshitha, set up my Amazon Beta account for Alexa and followed all the steps (and more) that your team's instructions said to. I could never find the Dev Skills tab in the Alexa app. I clicked on the Enable Alexa skill "o'hana!" link again and I got this error that I cannot add the skill to my account.

<img width="625" alt="screen shot 2018-06-09 at 1 16 16 pm" src="https://user-images.githubusercontent.com/5210136/41195701-86636672-6be7-11e8-8542-f702accd5252.png">

**Comment by johnwjlim** [comment]
Hey Andrew, 

Would you be able to give us the email that you'll be using to test the skill? We'll make sure to add that to the guest list ;)

Cheers

**Comment by abegel** [comment]
abegel@andrewbegel.com<mailto:abegel@andrewbegel.com>

Andy

**Comment by abegel** [comment]
Thanks! I think we're in business now.

**Comment by johnwjlim** [comment]
Sweet! glad that worked out!

**Comment by johnwjlim** [comment]
Sweet! glad that worked out!
